### ISSUE TITLE
signal abort when using boost recursive_directory_iterator

### ISSUE THREAD

**Issue by ArmstrongCN** [rttrorg/rttr#150] opened 2018-04-07 05:54 UTC
boost 1.64
cygwin
RTTR_VERSION       907

sample code:
```c++
#include <iostream>
#include <boost/filesystem.hpp>
int main() {
    boost::filesystem::recursive_directory_iterator it(boost::filesystem::path("./"));
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```
it will get signal abort if link with RTTR::Core_Lib.

fails on boost/filesystem/operations: directory_iterator_construct: Line 2391
```c++
it.m_imp->dir_entry.assign(p / filename, file_stat, symlink_file_stat);
```

**Comment by acki-m** [comment] 2018-04-07 11:49
maybe, you have some linking issues, with the STL? The linked version of the executable is different from the one in RTTR? Try linking against the DLL.
When you not invoke any code from RTTR, I don't see a problem in RTTR.

**Comment by ArmstrongCN** [comment] 2018-04-07 12:47
The unit_test.exe received signal abort too.

```bash
git clone https://github.com/rttrorg/rttr.git
cd rttr
mkdir build
cd build
cmake ..
make
```

```bash
[ 96%] Building CXX object src/unit_tests/CMakeFiles/unit_tests.dir/variant_associative_view/variant_associative_view_test.cpp.o
[ 97%] Building CXX object src/unit_tests/CMakeFiles/unit_tests.dir/variant_sequential_view/variant_sequential_view_test.cpp.o
[ 98%] Building RC object src/unit_tests/CMakeFiles/unit_tests.dir/version.rc.obj
[ 99%] Linking CXX executable ../../bin/unit_tests.exe
[ 99%] Built target unit_tests
Scanning dependencies of target run_tests
[100%] Running unit_tests
make[2]: *** [src/unit_tests/CMakeFiles/run_tests.dir/build.make:58: src/unit_tests/CMakeFiles/run_tests] Aborted (core dumped)
make[1]: *** [CMakeFiles/Makefile2:207: src/unit_tests/CMakeFiles/run_tests.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by ArmstrongCN** [comment] 2018-04-07 14:48
gcc -v:
```bash
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-6.4.0-5.x86_64/src/gcc-6.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-6.4.0-5.x86_64/src/gcc-6.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 6.4.0 (GCC)
```

cmake output:
```bash
-- The CXX compiler identification is GNU 6.4.0
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Project version: 0.9.7
-- Architecture: x64
-- Enabled: use of RTTI
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Failed
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Success
-- Performing Test HAS_CXX_CONSTEXPR
-- Performing Test HAS_CXX_CONSTEXPR - Success
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS - Success
-- using C++: 14
--
-- Finding 3rd party libs...
-- ===========================
-- Finished finding 3rd party libs!
CMake Warning at CMake/installer.cmake:60 (message):
  This system is not supported for packing
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)


-- Scanning rttr module.
-- ===========================
-- rttr directory included
-- Scanning rttr module finished!
--
-- Scanning unit_tests module.
-- ===========================
-- unit_tests directory included
-- Scanning unit_test_plugin module.
-- ===========================
-- plugin directory included
-- Scanning unit_test_plugin module finished!
--
-- Scanning unit_tests module finished!
--
-- Scanning json_example module.
-- ===========================
-- files directory included
-- Scanning json_example module finished!
--
-- Scanning library_loader_example module.
-- ===========================
-- files directory included
-- Scanning library_loader_example module finished!
--
-- Scanning plugin_example module.
-- ===========================
-- files directory included
-- Scanning plugin_example module finished!
--
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Warning at doc/CMakeLists.txt:85 (message):
  Doxygen not found - Documentation will not be generated!
```

cygwin stackdump:
```bash
cat src/unit_tests/unit_tests_d.exe.stackdump
Stack trace:
Frame        Function    Args
000FFFFAF10  0018005CF5C (00000000000, 0000000F948, 000FFFFB200, 000FFFFDE50)
000FFFFAFB0  0018005E56B (00100B09028, 00600000000, 000000000F8, 00000000000)
000FFFFB200  0018012132D (0000001CA00, 000FFFFB3B0, 005EB06DF88, 000FFFFB3B0)
00180010000  0018011DB0E (005EB09C500, 00000000000, 00000000000, 000FFFFB478)
000FFFFB6F0  0018011DFC2 (00000000000, 00180201280, 00000000002, 00000000006)
000FFFFB6F0  0018011E20A (005EB005049, 000FFFFB5F0, 00100ABF71B, 00000000000)
000FFFFB6F0  0018011E4CF (005EB118050, 000FFFFB620, 00100ABFB28, 00000000000)
000FFFFB6F0  001801575E6 (003F43A5E39, 00000000000, 000FFFFB69F, 005EB118050)
000FFFFB6F0  001800BA6D3 (000FFFFB6A0, 000FFFFB69F, 0060001D300, 005EB0C4118)
000FFFFB6F0  0018011973B (000FFFFB6A0, 000FFFFB69F, 0060001D300, 005EB0C4118)
000FFFFB6F0  001007DD539 (000FFFFBC80, 001008BEE80, 005EB0C7F0C, 0060001A7C0)
000FFFFB780  0010087F294 (000FFFFBA90, 000FFFFB830, 001008BF083, 000FFFFBB20)
000FFFFB810  001008BF2BD (0060005E660, 000FFFFBA90, 005EAFFA1BF, 001008BEE80)
000FFFFBAE0  005EB079E23 (000FFFFBC80, 000FFFFBB20, 000FFFFBB18, 000FFFFBC68)
000FFFFBB50  005EB07A4F1 (000FFFFBC80, 000FFFFBC68, 00000000000, 00180140131)
000FFFFBC00  005EB0798A3 (0060005E660, 000FFFFBC5F, 000FFFFC1F0, 000FFFFBC20)
End of stack trace (more stack frames may be present)
```

cygwin1.dll part:

```bash
awk '/^[0-9]/ { print $2 }' src/unit_tests/unit_tests_d.exe.stackdump | addr2line -f -e /usr/bin/cygwin1.dll
_ZN16cygwin_exceptionC4EPyP8_CONTEXTP17_EXCEPTION_RECORD
/usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/exception.h:174
__readgsqword
/usr/x86_64-pc-cygwin/sys-root/usr/include/w32api/psdk_inc/intrin-impl.h:714
_Z8sig_sendP6_pinfoR9siginfo_tP7_cygtls
/usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/sigproc.cc:736
_ZN6_pinfo4killER9siginfo_t
/usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/signal.cc:249
_ZN5pinfoD4Ev
/usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/pinfo.h:169
raise
/usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/signal.cc:286
__readgsqword
/usr/x86_64-pc-cygwin/sys-root/usr/include/w32api/psdk_inc/intrin-impl.h:714
dlfree
/usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/malloc.cc:4780
__readgsqword
/usr/x86_64-pc-cygwin/sys-root/usr/include/w32api/psdk_inc/intrin-impl.h:714
??
/cygwin/src/cygwin/cygwin-2.10.0/cygwin-2.10.0-1.x86_64/build/x86_64-pc-cygwin/winsup/cygwin/sigfe.s:43
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
```

cygrttr_core_d-0.9.7.dll:

```bash
awk '/^[0-9]/ { print $2 }' src/unit_tests/unit_tests_d.exe.stackdump | addr2line -f -e bin/cygrttr_core_d-0.9.7.dll
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
_ZNK4rttr7variant25try_basic_type_conversionISsEEbRT_
/cygdrive/c/rttr/src/rttr/detail/variant/variant_impl.h:228
_ZNK4rttr7variant7convertISsEEbRT_
/cygdrive/c/rttr/src/rttr/detail/variant/variant_impl.h:323
_ZNK4rttr7variant12convert_implISsEENSt9enable_ifIXaantsrSt13is_arithmeticIT_E5valuentsrSt7is_enumIS4_E5valueES4_E4typeEPb
/cygdrive/c/rttr/src/rttr/detail/variant/variant_impl.h:366
```

unit_tests_d.exe:

```bash
awk '/^[0-9]/ { print $2 }' src/unit_tests/unit_tests_d.exe.stackdump | addr2line -f -e bin/unit_tests_d.exe
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
_ZN4rttr6detail17convert_from_enumI10E_MetaDataE2toERKS2_RSs
/cygdrive/c/rttr/src/rttr/detail/variant/variant_data_converter.h:1434
_ZN4rttr6detail22default_type_converterI10E_MetaDataNS0_17convert_from_enumIS2_EEE10convert_toERKS2_RNS_8argumentE
/cygdrive/c/rttr/src/rttr/detail/variant/variant_data_converter.h:88
_ZN4rttr6detail24variant_data_base_policyI10E_MetaDataNS0_25variant_data_policy_smallIS2_NS0_20empty_type_converterIS2_EEEENS0_22default_type_converterIS2_NS0_17convert_from_enumIS2_EEEEE6invokeENS0_24variant_policy_operationERKNSt15aligned_storageILm8ELm8EE4typeENS0_16argument_wrapperE
/cygdrive/c/rttr/src/rttr/detail/variant/variant_data_policy.h:313
??
??:0
??
??:0
??
??:0
```

**Comment by acki-m** [comment] 2018-04-07 18:39
Mhm...very interesting.
Do you have also another compiler for testing? E.g. mingw?

**Comment by ArmstrongCN** [comment] 2018-04-08 05:28
msys2
GNU 6.4.0

stacktrace:
```bash
cat src/unit_tests/unit_tests_d.exe.stackdump
Stack trace:
Frame        Function    Args
000FFFFAF10  0018005D16C (00000000000, 0060000FA80, 00000000000, 000FFFFDE50)
000FFFFAFB0  0018005E77B (00100B09028, 00600000000, 000000001F4, 00000000000)
000FFFFB200  00180123ACD (0000001CA70, 000FFFFB3B0, 00498E0DF88, 000FFFFB3B0)
00180010000  001801202AE (00498E3C500, 00000000000, 00000000000, 000FFFFB478)
000FFFFB6F0  00180120762 (00000000000, 00180204280, 00000000002, 00000000006)
000FFFFB6F0  001801209AA (00498DA5049, 000FFFFB5F0, 00100ABF71B, 00000000000)
000FFFFB6F0  00180120C6F (00498EB8050, 000FFFFB620, 00100ABFB28, 00000000000)
000FFFFB6F0  0018015A0C6 (005268A5E29, 00000000000, 000FFFFB69F, 00498EB8050)
000FFFFB6F0  001800BA8E3 (000FFFFB6A0, 000FFFFB69F, 0060001D370, 00498E64118)
000FFFFB6F0  0018011BEDB (000FFFFB6A0, 000FFFFB69F, 0060001D370, 00498E64118)
000FFFFB6F0  001007DD539 (000FFFFBC80, 001008BEE80, 00498E67F0C, 0060001A830)
000FFFFB780  0010087F294 (000FFFFBA90, 000FFFFB830, 001008BF083, 000FFFFBB20)
000FFFFB810  001008BF2BD (0060005E6D0, 000FFFFBA90, 00498D9A1BF, 001008BEE80)
000FFFFBAE0  00498E19E23 (000FFFFBC80, 000FFFFBB20, 000FFFFBB18, 000FFFFBC68)
000FFFFBB50  00498E1A4F1 (000FFFFBC80, 000FFFFBC68, 00000000000, 00180142BC1)
000FFFFBC00  00498E198A3 (0060005E6D0, 000FFFFBC5F, 000FFFFC1F0, 000FFFFBC20)
End of stack trace (more stack frames may be present)
```

unit_tests_d.exe:
```bash
awk '/^[0-9]/ { print $2 }' src/unit_tests/unit_tests_d.exe.stackdump | addr2line -f -e bin/unit_tests_d.exe
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
_ZN4rttr6detail17convert_from_enumI10E_MetaDataE2toERKS2_RSs
/home/a/rttr/src/rttr/detail/variant/variant_data_converter.h:1434
_ZN4rttr6detail22default_type_converterI10E_MetaDataNS0_17convert_from_enumIS2_EEE10convert_toERKS2_RNS_8argumentE
/home/a/rttr/src/rttr/detail/variant/variant_data_converter.h:88
_ZN4rttr6detail24variant_data_base_policyI10E_MetaDataNS0_25variant_data_policy_smallIS2_NS0_20empty_type_converterIS2_EEEENS0_22default_type_converterIS2_NS0_17convert_from_enumIS2_EEEEE6invokeENS0_24variant_policy_operationERKNSt15aligned_storageILm8ELm8EE4typeENS0_16argument_wrapperE
/home/a/rttr/src/rttr/detail/variant/variant_data_policy.h:313
??
??:0
??
??:0
??
??:0
```

msys-rttr_core_d-0.9.7.dll:
```bash
 awk '/^[0-9]/ { print $2 }' src/unit_tests/unit_tests_d.exe.stackdump | addr2line -f -e bin/msys-rttr_core_d-0.9.7.dll
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
_ZNK4rttr7variant25try_basic_type_conversionISsEEbRT_
/home/a/rttr/src/rttr/detail/variant/variant_impl.h:228
_ZNK4rttr7variant7convertISsEEbRT_
/home/a/rttr/src/rttr/detail/variant/variant_impl.h:323
_ZNK4rttr7variant12convert_implISsEENSt9enable_ifIXaantsrSt13is_arithmeticIT_E5valuentsrSt7is_enumIS4_E5valueES4_E4typeEPb
/home/a/rttr/src/rttr/detail/variant/variant_impl.h:366
```

msys-2.0.dll:
```bash
awk '/^[0-9]/ { print $2 }' src/unit_tests/unit_tests_d.exe.stackdump | addr2line -f -e /usr/bin/msys-2.0.dll
_ZN16cygwin_exceptionC4EPyP8_CONTEXTP17_EXCEPTION_RECORD
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/exception.h:174
__readgsqword
/usr/include/w32api/psdk_inc/intrin-impl.h:772
_Z8sig_sendP6_pinfoR9siginfo_tP7_cygtls
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/sigproc.cc:736
_ZN6_pinfo4killER9siginfo_t
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/signal.cc:249
_ZN5pinfoD4Ev
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/pinfo.h:169
raise
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/signal.cc:286
__readgsqword
/usr/include/w32api/psdk_inc/intrin-impl.h:772
dlfree
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/malloc.cc:4780
__readgsqword
/usr/include/w32api/psdk_inc/intrin-impl.h:772
??
/msys_scripts/msys2-runtime/src/build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin/sigfe.s:43
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
```

**Comment by acki-m** [comment] 2018-04-08 09:32
I just run the test on my PC (VS2017 and mingw) not executed in the msys or cygwin shell) plain cmd shell.
Works without any problem.

The `??:0` are looking strane, what does it mean? It looks like some exception is thrown, in a function which is declared `noexcept`. Can you set a breakpoint near the location, so we can see that is really the case?

**Comment by ArmstrongCN** [comment] 2018-04-09 04:43
`??:0`   indicates that this frame is not in current dll/exe.  when combining all there addr2line output, we can have a complete trace.

**Comment by ArmstrongCN** [comment] 2018-04-10 04:47
```bash
Thread 1 "unit_tests_d" received signal SIGABRT, Aborted.
0x00000001007dd539 in rttr::detail::convert_from_enum<E_MetaData>::to (
    from=@0x98: <error reading variable>, to=...)
    at /home/a/rttr/src/rttr/detail/variant/variant_data_converter.h:1434
1434            to = get_enumeration_name(from).to_string();
(gdb) p from
$1 = (const E_MetaData &) @0x98: <error reading variable>
```

**Comment by ArmstrongCN** [comment] 2018-04-10 11:11
are there known issues with cygwin bash or msys bash ?

**Comment by acki-m** [comment] 2018-04-10 17:45
Cygwin is not tested via CI so that means there is currently no direct support for it.
However, I was able to compile rttr and reproduce the error within cygwin.
It seem to be an issue with cygwin itself.
During debug, the I had one crash because of std::string, when copying data to it.
I found several bug reports:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16612
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=24196

I also don't know what is the correct way to export a class inside cygwin, 
both approaches (using __declspec( dllexport ) and not using it) seems to work.
You can adjust the export macro here:
https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/base/core_prerequisites.h#L115
Then you have to remove the hidden flag here too:
https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/base/core_prerequisites.h#L123
Seems to be not supported by cygwin.
When I did this I was able to run the json example.

Maybe you know more about this topic, STL + Shared libraries in cygwin.

TL;TR
It seems to be an issue with cygwin and how things are exported and not with RTTR itself.

**Comment by acki-m** [comment] 2018-04-11 19:27
I will close this now, when you have a fix for this issue, I am happy about a PR from you (when there is something fixable).

**Closed by acki-m** 2018-04-11 19:27 UTC
